# Generated by Django 6.0.5 on 2026-06-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_administrativeboundary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeboundary',
            options={'verbose_name': 'Administrative Boundary', 'verbose_name_plural': 'Administrative Boundaries'},
        ),
    ]
