# Generated by Django 6.0.5 on 2026-06-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_administrativeboundary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeboundary',
            name='boundary_type',
            field=models.CharField(choices=[('region', 'Region')], default='region', max_length=100),
        ),
    ]
