# Generated by Django 6.0.5 on 2026-06-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='location',
            new_name='geom',
        ),
    ]
