# Generated by Django 6.0.5 on 2026-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_location_landmark_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundary_type',
            field=models.CharField(choices=[('district', 'District')], default='district', max_length=100),
        ),
    ]
