# Generated by Django 6.0.5 on 2026-07-08 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_district_boundary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('urban_type', models.CharField(max_length=100)),
                ('admin1_name', models.CharField(max_length=100)),
                ('admin1_pcode', models.CharField(max_length=30)),
                ('admin2_name', models.CharField(max_length=100)),
                ('admin2_pcode', models.CharField(max_length=30)),
                ('opz_name', models.CharField(blank=True, max_length=150)),
                ('opz_id_code', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
    ]
