# Generated by Django 6.0.5 on 2026-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='admin1_pcode',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='opz_id_code',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='opz_name',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='source',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='municipality',
            name='boundary_type',
            field=models.CharField(choices=[('mun', 'Municipality')], default='municipality', max_length=100),
        ),
    ]
