# Generated by Django 6.0.5 on 2026-07-09 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_municipality_admin1_pcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SURPII_Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin2Name', models.CharField(max_length=100)),
                ('admin2Pcod', models.CharField(max_length=30)),
                ('admin1Name', models.CharField(max_length=100)),
                ('UrbanName', models.CharField(max_length=100)),
                ('UrbanType', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SURPII Building',
                'verbose_name_plural': 'SURPII Buildings',
                'ordering': ['admin2Name'],
            },
        ),
    ]
