# Generated by Django 6.0.5 on 2026-07-09 17:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_surpii_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='SURPII_Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('highway', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50, null=True)),
                ('admin2Name', models.CharField(max_length=100)),
                ('admin2Pcod', models.CharField(max_length=30)),
                ('admin1Name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SURPII Road',
                'verbose_name_plural': 'SURPII Roads',
                'ordering': ['admin2Name', 'highway'],
            },
        ),
    ]
