# Generated by Django 6.0.5 on 2026-07-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_surpii_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surpii_road',
            name='name',
        ),
    ]
