# Generated by Django 6.0.5 on 2026-07-09 17:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_surpii_road_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surpii_road',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
