# Generated by Django 6.0.5 on 2026-07-09 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_surpii_road_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surpii_road',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
