# Generated by Django 6.0.5 on 2026-07-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_surpii_road_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surpii_road',
            name='admin2Pcod',
        ),
        migrations.RemoveField(
            model_name='surpii_road',
            name='surface',
        ),
    ]
