# Generated by Django 6.0.5 on 2026-07-10 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_surpii_road_admin2pcod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('river_class', models.IntegerField()),
                ('length_m', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'River',
                'verbose_name_plural': 'Rivers',
                'ordering': ['name'],
            },
        ),
    ]
