# Generated by Django 6.0.5 on 2026-07-10 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_river'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urbanName', models.CharField(blank=True, max_length=100, null=True)),
                ('urbanType', models.CharField(blank=True, max_length=100, null=True)),
                ('admin1Name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('settlementName', models.CharField(blank=True, max_length=150, null=True)),
                ('settlementClass', models.CharField(blank=True, max_length=100, null=True)),
                ('idpHouseholds', models.IntegerField(blank=True, null=True)),
                ('idpIndividuals', models.IntegerField(blank=True, null=True)),
                ('populationCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IDP Settlement',
                'verbose_name_plural': 'IDP Settlements',
                'ordering': ['urbanName', 'settlementName'],
            },
        ),
    ]
