# Generated by Django 6.0.5 on 2026-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_idp'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='settlementDTMId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
