# Generated by Django 6.0.5 on 2026-07-13 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_idp_settlementdtmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=254, unique=True)),
                ('event_date', models.DateField()),
                ('year', models.IntegerField(db_index=True)),
                ('disorder_type', models.CharField(blank=True, max_length=254, null=True)),
                ('event_type', models.CharField(blank=True, max_length=254, null=True)),
                ('sub_event_type', models.CharField(blank=True, max_length=254, null=True)),
                ('actor1', models.CharField(blank=True, max_length=254, null=True)),
                ('associated_actor1', models.CharField(blank=True, max_length=254, null=True)),
                ('actor2', models.CharField(blank=True, max_length=254, null=True)),
                ('associated_actor2', models.CharField(blank=True, max_length=254, null=True)),
                ('civilian_targeting', models.CharField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('admin1', models.CharField(blank=True, max_length=254, null=True)),
                ('admin2', models.CharField(blank=True, max_length=254, null=True)),
                ('admin3', models.CharField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fatalities', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conflict Event',
                'verbose_name_plural': 'Conflict Events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['year'], name='manager_con_year_5785ff_idx'), models.Index(fields=['admin1'], name='manager_con_admin1_60cd80_idx'), models.Index(fields=['admin2'], name='manager_con_admin2_e96b2d_idx'), models.Index(fields=['event_type'], name='manager_con_event_t_a991f6_idx')],
            },
        ),
    ]
