# Generated by Django 6.0.5 on 2026-07-13 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_conflictevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floodClass', models.CharField(max_length=100)),
                ('admin2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('areaHa', models.FloatField(blank=True, null=True)),
                ('shapeArea', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historical Flood Extent',
                'verbose_name_plural': 'Historical Flood Extents',
                'ordering': ['admin2Name', 'floodClass'],
            },
        ),
    ]
