# Generated by Django 6.0.5 on 2026-07-13 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_floodextent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodextent',
            options={'verbose_name': 'Historical Flood Extent', 'verbose_name_plural': 'Historical Flood Extents'},
        ),
        migrations.RemoveField(
            model_name='floodextent',
            name='admin2Name',
        ),
        migrations.RemoveField(
            model_name='floodextent',
            name='areaHa',
        ),
        migrations.RemoveField(
            model_name='floodextent',
            name='floodClass',
        ),
        migrations.RemoveField(
            model_name='floodextent',
            name='shapeArea',
        ),
        migrations.AlterField(
            model_name='floodextent',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
