# Generated by Django 6.0.5 on 2026-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_municipalityexposuresummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='flood_exposed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='surpii_building',
            name='flood_exposed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='surpii_road',
            name='flood_exposed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
